version: "3"

volumes:
    mongodb_volume:

services:
    nginx:
        image: nginx:1
        container_name: production_nginx
        volumes:
            - ./conf/nginx/router.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/snippets:/etc/nginx/snippets
            - ./conf/nginx/logs/:/var/log/nginx/
            - /etc/letsencrypt/:/etc/letsencrypt/
        ports:
            - 80:80
            - 443:443
        restart: always
    # certbot:
    #     container_name: certbot
    #     image: certbot/certbot
    #     volumes:
    #         - ./conf/nginx/data/certbot/conf/:/etc/letsencrypt/
    #         - ./conf/nginx/data/certbot/www/:/var/www/certbot/
    #     restart: always
    #     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    images_organizer:
        container_name: images_organizer
        build: ./
        expose:
            - "80"
        ports:
            - 3000:80
    recognition_service:
        container_name: recognition_service
        build:
            context: ./services
            dockerfile: Dockerfile
        expose:
            - "5000"
        ports:
            - 5000:5000
        restart: always
    mongodb:
        image: mongo:4.2.6
        volumes:
            - mongodb_volume:/data/db
        restart: always
    faceted_search:
        container_name: faceted_search
        environment:
            - MONGODB_HOST=mongodb
            - PORT=80
        build:
            context: ./faceted_search/
            dockerfile: ./Dockerfile
        expose:
            - "8000"
        ports:
            - 8000:80
    rcm:
        container_name: rcm
        build:
            context: ./rcm
            dockerfile: ./Dockerfile
        expose:
            - "3000"
        ports:
            - 6000:3000
