version: "3"

volumes:
    mongodb_volume:
    io_codebase_volume:
    tagger_codebase_volume:

services:
    nginx:
        image: nginx:1
         container_name: production_nginx
        volumes:
            - ./conf/nginx/custom.conf:/etc/nginx/conf.d/default.conf
            # - ./conf/nginx/https.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/snippets:/etc/nginx/snippets
            - ./conf/nginx/logs/:/var/log/nginx/
            - /etc/letsencrypt/:/etc/letsencrypt/
            - tagger_codebase_volume:/var/www/tagger
            - io_codebase_volume:/var/www/io
        ports:
            - 80:80
            - 443:443
        restart: always
    tagger_client:
        env_file: ./tagger/tagger-for-david/.env
        volumes:
            - tagger_codebase_volume:/app/dev/codebase
        build:
            context: ./tagger/tagger-for-david/
            dockerfile: ./Dockerfile
    tagger_backend:
        env_file: ./tagger/tagger-for-david/.env
        environment:
            - MONGODB_HOST=mongodb
        build:
            context: ./tagger/tagger-for-david/
            dockerfile: sources/server/Dockerfile
        ports:
            - "4000:4000"
        restart: always
    images_organizer:
        volumes:
            - io_codebase_volume:/app/dev/codebase
        build: ./
    mongodb:
        image: mongo:4.2.6
        volumes:
            - mongodb_volume:/data/db
        restart: always
