version: "3"

volumes:
    mongodb_tagger_volume:

services:
    tagger_client:
        depends_on:
            - tagger_backend
        container_name: tagger_client
        env_file: ./.env
        build:
            context: .
            dockerfile: ./Dockerfile
        expose:
            - "80"
        ports:
            - 2000:80
    tagger_backend:
        depends_on:
            - mongodb
        container_name: tagger_backend
        env_file: ./.env
        build:
            context: .
            dockerfile: sources/server/Dockerfile
        expose:
            - "4000"
        ports:
            - 4000:4000
        restart: unless-stopped
        environment:
            - DB_HOST=mongodb
            - DB_USER=$MONGODB_USER
            - DB_PASSWORD=$MONGODB_PASSWORD
            - DB_NAME=$MONGODB_DATABASE
            - DB_PORT=$MONGODB_DOCKER_PORT
    mongodb:
        image: mongo:4.2.6
        volumes:
            - mongodb_tagger_volume:/data/db
            - "./users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro"
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
        expose:
            - $MONGODB_DOCKER_PORT
        ports:
            - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT


