version: "3"

volumes:
        mongodb_volume:

services:
        client:
                env_file: .env
                environment:
                        - TAGGER_API_PATH=$TAGGER_API_PATH
                volumes:
                        - /srv/david-gutman-tagger/conf/nginx/:/etc/nginx/sites-available
                build: ./
                ports:
                        - "80:80"
                restart: always
        server:
                env_file: .env
                environment:
                        - MONGODB_NAME=$MONGODB_NAME
                        - MONGODB_PORT=$MONGODB_PORT
                        - MONGODB_HOST=mongodb
                        - SECRET_KEY=$SECRET_KEY
                build:
                        context: ./
                        dockerfile: sources/server/Dockerfile
                ports:
                        - "4000:4000"
                restart: always
        mongodb:
                image: mongo:latest
                volumes:
                        - mongodb_volume:/data/db
                restart: always
