FROM ubuntu:18.04

RUN apt update -y

RUN apt-get -y install curl gnupg

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -

RUN apt install nginx -y

RUN apt install nodejs -y

RUN apt install git -y
